STO.WebUI/Controllers/NavigationController.cs
using Newtonsoft.Json;
using STO.Domain.Concrete;
using STO.Domain.Entities;
using STO.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using STO.WebUI.Filters;
using STO.Domain.DAL;
using STO.WebUI.Service;

namespace STO.WebUI.Controllers
{
    [Culture]
    public class NavigationController : Controller
    {
        EFDbContext db = new EFDbContext("EFDbContext");

        private readonly UnitOfWork _unitOfWork;

        public NavigationController(UnitOfWork unitofWork)
        {
            _unitOfWork = unitofWork;
        }

        //[HttpGet]
        //[ChildActionOnly]
        //public ActionResult PViewTotalPrice()
        //{

        //    int count = Convert.ToInt32(WebConfigurationManager.AppSettings["ListLastCars"]);
        //    List<TotalPrice> totalPrices = db.TotalPrices.OrderByDescending(o => o.Date)
        //        .Include(c => c.Car).Take(count)
        //        .ToList();
        //    ViewData["ListLastCars"] = count;
        //    return PartialView("PViewTotalPrice", totalPrices);
        //}

        [HttpGet]
        public ActionResult Details(int id)
        {
            //TotalPrice totalPrice = db.TotalPrices
            //    .Include(c => c.Car.TypeCar)
            //    .Include(l => l.CalculateCost.Select(cc => cc.TypeService.Service))
            //    //.OrderBy(s => s.CalculateCost.OrderBy(t => t.TypeService.Service.IsAddService))
            //    .FirstOrDefault(p => p.Id == id);
            //ViewBag.IsContainAddService =
            //    totalPrice?.CalculateCost.FirstOrDefault(s => s.TypeService.Service.IsAddService) != null;
            //totalPrice?.CalculateCost.OrderBy(s => s.TypeService.Service.IsAddService);
            //return View(totalPrice);
            return null;
        }

        public ActionResult Language()
        {
            return PartialView("ChangeLanguage");
        }

        public ActionResult ChangeLanguage(string lang)
        {
            // Список культур
            List<string> cultures = new List<string>() { "ru", "en" };
            if (!cultures.Contains(lang))
            {
                lang = "ru";
            }
            // Сохраняем выбранную культуру в куки
            HttpCookie cookie = Request.Cookies["lang"];
            if (cookie != null)
                cookie.Value = lang;   // если куки уже установлено, то обновляем значение
            else
            {
                cookie = new HttpCookie("lang");
                cookie.HttpOnly = false;
                cookie.Value = lang;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);
            return Redirect(Request.UrlReferrer?.AbsolutePath);  /*PartialView(); *///Redirect(Request.UrlReferrer.AbsolutePath);
        }
    }
}

STO.WebUI/Views/Navigation/ChangeLanguage.cshtml
@Html.ActionLink("En", "ChangeLanguage", "Navigation", new
{
    lang = "en"
}, null)

@Html.ActionLink("Ru", "ChangeLanguage", "Navigation", new
{
    lang = "ru"
}, null)

STO.WebUI/Views/Navigation/Details.cshtml
@model  STO.Domain.Entities.TotalPrice

@using STO.WebUI.Resources.View

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    bool addService = true;
}
@helper AddRow(string name, object value, bool shift = true)
    {
        var styleName = shift ? "col-6 col-md-4" : "col-6 col-md-4 ml-3";
        var styleValue = shift ? "col-6 col-md-4 ml-3" : "col-6 col-md-4 mr-3";

        <div class="row">
            <div class="@styleName">@name</div>
            <div class="@styleValue">@value</div>
        </div>
}
@*<h2>@Resources.Resource</h2>*@

<h2>@DetailsRes.Culture</h2>

<h2>Краткая информация</h2>
@*@AddRow("Номер автомобиля:", @Model.Car.Number)*@
@AddRow("Тип автомобиля:", @Model.Car.TypeCar.Name)
@AddRow("Дата:", @Model.Date)
@AddRow("Состояние автомобиля:", @Model.AvgState)
@AddRow("Услуги:", "(ед.)")

@{
    foreach (var item in @Model.CalculateCost)
    {
        if (!item.TypeService.Service.IsAddService)
        {
            @AddRow(@item.TypeService.Service.Name, @item.State, false)
        }
        else
        {
            if (addService)
            {
                addService = false;
                @AddRow("Дополнительные услуги:", "(грн.)")
            }
            @AddRow(@item.TypeService.Service.Name, @item.TypeService.Service.Cost, false)
        }
    }
}
<br />
@AddRow(null, $"К оплате всего {@Model.Total} денег")

STO.WebUI/Views/Navigation/PViewTotalPrice.cshtml
@model  IEnumerable<STO.Domain.Entities.TotalPrice>
     Последниие @ViewData["ListLastCars"]-ть записей:
    <br />
<div class="list-group">

    @foreach (var item in Model)
    {

        @Html.RouteLink(@item.Car.Number.ToString(), new
        {
            controller = "Navigation",
            action = "Details",
            id = @item.Id
        }, new { @class = "list-group-item" })
    }
</div>